### Exercises

In [114]:
import pandas as pd

#### Exercise 1

Load the `nyc_food.csv` dataset into a Pandas DataFrame called `df`.

1. Display the first 5 rows of the dataset.
2. How many rows and columns does the dataset contain?
3. What are the names of all the columns?
4. What are the data types of each column?

In [115]:
# PUT YOUR CODE HERE
df = pd.read_csv("../data/nyc_food.csv")

df.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1898 entries, 0 to 1897
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1898 non-null   int64
 1   customer_id            1898 non-null   int64
 2   restaurant_name        1898 non-null   object
 3   cuisine_type           1898 non-null   object
 4   cost_of_the_order      1898 non-null   float64
 5   day_of_the_week        1898 non-null   object
 6   rating                 1898 non-null   object
 7   food_preparation_time  1898 non-null   int64
 8   delivery_time          1898 non-null   int64
dtypes: float64(1), int64(4), object(4)
memory usage: 133.6+ KB

In [117]:
df.columns

Index(['order_id', 'customer_id', 'restaurant_name', 'cuisine_type',
       'cost_of_the_order', 'day_of_the_week', 'rating',
       'food_preparation_time', 'delivery_time'],
      dtype='object')

#### Exercise 2

1. Generate a summary of the dataset’s numerical columns using a single Pandas function.
2. What are the unique values for cuisine type?

In [118]:
df.describe()

,order_id,customer_id,cost_of_the_order,food_preparation_time,delivery_time
count,1.898000e+03,1898.000000,1898.000000,1898.000000,1898.000000
mean,1.477496e+06,171168.478398,16.498851,27.371970,24.161749
std,5.480497e+02,113698.139743,7.483812,4.632481,4.972637
min,1.476547e+06,1311.000000,4.470000,20.000000,15.000000
25%,1.477021e+06,77787.750000,12.080000,23.000000,20.000000
50%,1.477496e+06,128600.000000,14.140000,27.000000,25.000000
75%,1.477970e+06,270525.000000,22.297500,31.000000,28.000000
max,1.478444e+06,405334.000000,35.410000,35.000000,33.000000

In [119]:
print(df["cuisine_type"].unique())

['Korean' 'Japanese' 'Mexican' 'American' 'Indian' 'Italian'
 'Mediterranean' 'Chinese' 'Middle Eastern' 'Thai' 'Southern' 'French'
 'Spanish' 'Vietnamese']

#### Exercise 3

1. Select all rows where the cuisine description is `"Chinese"`.
2. From that filtered DataFrame, display only the columns for restaurant name and cost of order.
3. Further filter the results to only include restaurants with an order cost greater than 30.
4. How many rows satisfy all of these conditions?

#### Exercise 4

1. Select only the columns related to restaurant name, cuisine type, and rating, and store this in a new DataFrame called `df_subset`.
2. Use `.loc` to select rows from `df_subset` with index labels from 10 to 20 (inclusive) and display them.
3. Use `.iloc` to select the first 5 rows and the first 3 columns of `df_subset`.

Exercise 3 Answers

In [120]:
cuisine = df.loc[
(df["cuisine_type"] == "Chinese") & (df["cost_of_the_order"] > 30) , ["restaurant_name", "cost_of_the_order"]] 
print(cuisine)

                  restaurant_name  cost_of_the_order
92                 RedFarm Hudson              33.03
137                   CafÌ© China              32.93
156              RedFarm Broadway              31.33
221                   Han Dynasty              33.03
299                RedFarm Hudson              32.93
725              RedFarm Broadway              32.98
970              RedFarm Broadway              31.86
1066               RedFarm Hudson              33.03
1173                  Han Dynasty              33.03
1616             RedFarm Broadway              31.87
1646                  Han Dynasty              34.19
1821  Grand Sichuan International              32.93
1868             RedFarm Broadway              31.43

13 rows satisfy all of these conditions

In [121]:
cuisine.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 92 to 1868
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   restaurant_name    13 non-null     object
 1   cost_of_the_order  13 non-null     float64
dtypes: float64(1), object(1)
memory usage: 312.0+ bytes

Exercise 4 Answers

In [122]:
df_subset = df.iloc[:, [2,3,6]]
df_subset.head()

             restaurant_name cuisine_type     rating
0                    Hangawi       Korean  Not given
1  Blue Ribbon Sushi Izakaya     Japanese  Not given
2                Cafe Habana      Mexican          5
3  Blue Ribbon Fried Chicken     American          3
4           Dirty Bird to Go     American          4

In [123]:
df_subset.loc[10:20]

                restaurant_name   cuisine_type     rating
10   Big Wong Restaurant _¤¾Ñ¼        Chinese  Not given
11       Empanada Mama (closed)        Mexican          5
12    Blue Ribbon Fried Chicken       American          5
13                        Pylos  Mediterranean          3
14       Lucky's Famous Burgers       American  Not given
15                  Shake Shack       American          5
16                Sushi of Gari       Japanese  Not given
17    Blue Ribbon Sushi Izakaya       Japanese  Not given
18               RedFarm Hudson        Chinese          4
19            Blue Ribbon Sushi       Japanese          4
20  Five Guys Burgers and Fries       American          4

In [124]:
df_subset.iloc[:5,:3]

             restaurant_name cuisine_type     rating
0                    Hangawi       Korean  Not given
1  Blue Ribbon Sushi Izakaya     Japanese  Not given
2                Cafe Habana      Mexican          5
3  Blue Ribbon Fried Chicken     American          3
4           Dirty Bird to Go     American          4

#### Exercise 5

1. Sort the DataFrame by the order cost column in descending order and display the top 10 rows.
2. Sort the DataFrame by cuisine type and then by delivery time.
3. Create a new column called `cost_category`:
   - Assign `"High"` if the order cost is greater than 30
   - Assign `"Medium"` if the score is in (20, 30]
   - Assign `"Low"` if the score is less than or equal to 20
5. Display the first 10 rows of the DataFrame including this new column.

In [125]:
df.sort_values(by=["cost_of_the_order"], ascending = False).head(10)

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
573,1477814,62359,Pylos,Mediterranean,35.41,Weekday,4,21,29
1646,1477665,231061,Han Dynasty,Chinese,34.19,Weekday,Not given,21,31
1762,1477700,60039,Blue Ribbon Sushi,Japanese,33.37,Weekday,3,30,27
1831,1476970,275689,Nobu Next Door,Japanese,33.37,Weekend,4,32,21
1370,1478329,116992,Tres Carnes,Mexican,33.32,Weekday,4,21,33
41,1478143,337525,TAO,Japanese,33.22,Weekend,Not given,23,19
1213,1476695,68300,Blue Ribbon Fried Chicken,American,33.18,Weekend,Not given,26,20
92,1478211,154030,RedFarm Hudson,Chinese,33.03,Weekend,4,26,22
64,1478077,82041,Shake Shack,American,33.03,Weekday,Not given,22,32
1007,1478404,97991,Blue Ribbon Sushi Bar & Grill,Japanese,33.03,Weekend,5,28,15

In [126]:
df.sort_values(by=["cuisine_type","delivery_time"])

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15
122,1477255,50199,Five Guys Burgers and Fries,American,12.13,Weekend,Not given,26,15
189,1478417,87747,Blue Ribbon Fried Chicken,American,9.02,Weekend,5,31,15
195,1477004,250494,Five Guys Burgers and Fries,American,33.03,Weekend,5,29,15
248,1477679,120833,Bareburger,American,16.25,Weekend,Not given,29,15
...,...,...,...,...,...,...,...,...,...
746,1477189,54630,V-Nam Cafe,Vietnamese,22.26,Weekend,5,33,26
1272,1477555,361497,V-Nam Cafe,Vietnamese,12.13,Weekend,4,20,26
640,1477799,399520,Xe May Sandwich Shop,Vietnamese,14.07,Weekday,Not given,28,28
373,1477014,399520,Xe May Sandwich Shop,Vietnamese,7.96,Weekend,5,25,29
1164,1478373,40808,V-Nam Cafe,Vietnamese,6.01,Weekday,3,20,31

In [130]:
df.loc[df["cost_of_the_order"] > 30, "cost_category"] = "High"
df.loc[(df["cost_of_the_order"] > 20) & (df["cost_of_the_order"] <= 30), "cost_category"] = "Medium"
df.loc[df["cost_of_the_order"] <= 20, "cost_category"] = "Low"

#### Exercise 6

1. Create a new column called `total_time` by adding the preparation and delivery times.
2. Remove the day of week column
5. Rename the cost column so that it is simply called `order_cost`

In [50]:
df["total_time"] = df["food_preparation_time"] + df["delivery_time"]
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,day_of_the_week,rating,food_preparation_time,delivery_time,cost_category,total_time
0,1477147,337525,Hangawi,Korean,30.75,Weekend,Not given,25,20,High,45
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Weekend,Not given,25,23,Low,48
2,1477070,66393,Cafe Habana,Mexican,12.23,Weekday,5,23,28,Low,51
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,Weekend,3,25,15,Medium,40
4,1478249,76942,Dirty Bird to Go,American,11.59,Weekday,4,25,24,Low,49

In [53]:
df.drop(columns = ["day_of_the_week"], inplace = True)
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,cost_of_the_order,rating,food_preparation_time,delivery_time,cost_category,total_time
0,1477147,337525,Hangawi,Korean,30.75,Not given,25,20,High,45
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Not given,25,23,Low,48
2,1477070,66393,Cafe Habana,Mexican,12.23,5,23,28,Low,51
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,3,25,15,Medium,40
4,1478249,76942,Dirty Bird to Go,American,11.59,4,25,24,Low,49

In [55]:
df.rename(columns = {"cost_of_the_order": "order_cost"}, inplace = True)
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,order_cost,rating,food_preparation_time,delivery_time,cost_category,total_time
0,1477147,337525,Hangawi,Korean,30.75,Not given,25,20,High,45
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Not given,25,23,Low,48
2,1477070,66393,Cafe Habana,Mexican,12.23,5,23,28,Low,51
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,3,25,15,Medium,40
4,1478249,76942,Dirty Bird to Go,American,11.59,4,25,24,Low,49

#### Exercise 7

1. Use the `map` method to create a new column named `is_expensive` that is 1 if the order cost is greater than 30 and is 0 otherwise.
2. Use the `apply` method to create a new column named `fast_favorite` which is 1 if the cuisine type is `"Japanese"` and the cost is below 20 dollars and is 0 otherwise

In [64]:
df["is_expensive"] = df["order_cost"].map(
    lambda x: 1 if x > 30 
    else 0
)
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,order_cost,rating,food_preparation_time,delivery_time,cost_category,total_time,is_expensive
0,1477147,337525,Hangawi,Korean,30.75,Not given,25,20,High,45,1
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Not given,25,23,Low,48,0
2,1477070,66393,Cafe Habana,Mexican,12.23,5,23,28,Low,51,0
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,3,25,15,Medium,40,0
4,1478249,76942,Dirty Bird to Go,American,11.59,4,25,24,Low,49,0

In [73]:
df["fast_favorite"] = df.apply(
    lambda row: 1 if (row["cuisine_type"] == "Japanese" and row["order_cost"] < 20)
                 else 0, axis = 1
)
df.head()

,order_id,customer_id,restaurant_name,cuisine_type,order_cost,rating,food_preparation_time,delivery_time,cost_category,total_time,is_expensive,fast_favorite
0,1477147,337525,Hangawi,Korean,30.75,Not given,25,20,High,45,1,0
1,1477685,358141,Blue Ribbon Sushi Izakaya,Japanese,12.08,Not given,25,23,Low,48,0,1
2,1477070,66393,Cafe Habana,Mexican,12.23,5,23,28,Low,51,0,0
3,1477334,106968,Blue Ribbon Fried Chicken,American,29.20,3,25,15,Medium,40,0,0
4,1478249,76942,Dirty Bird to Go,American,11.59,4,25,24,Low,49,0,0

#### Exercise 8

1. Use the `map` method to create a column named `cuisine_short` that implements the following mapping:
   - Korean: KO
   - Japanese: JA
   - Mexican: MX
   - American: AM
   - Indian: IN
   - Italian: IT
   - Mediterranean: MD
   - Chinese: CH
   - Middle Eastern: ME
   - Thai: TH
   - Southern: SO
   - French: FR
   - Spanish: SP
   - Vietnamese: VT

In [77]:
df["cuisine_type"].unique()

array(['Korean', 'Japanese', 'Mexican', 'American', 'Indian', 'Italian',
       'Mediterranean', 'Chinese', 'Middle Eastern', 'Thai', 'Southern',
       'French', 'Spanish', 'Vietnamese'], dtype=object)

In [81]:
cuisine_dict = {
    "Korean": "KO",
    "Japanese": "JA",
    "Mexican": "MX",
    "American": "AM",
    "Indian": "IN",
    "Italian": "IT",
    "Mediterranean": "MD",
    "Chinese": "CH",
    "Middle Eastern": "ME",
    "Thai": "TH",
    "Southern": "SO",
    "French": "FR",
    "Spanish": "SP",
    "Vietnamese": "VT"
}

df["cuisine_short"] = df["cuisine_type"].map(cuisine_dict)

df["cuisine_short"].head()

0    KO
1    JA
2    MX
3    AM
4    AM
Name: cuisine_short, dtype: object

#### Exercise 9

1. Group the data by cuisine type and calculate the average order cost for each cuisine.
2. For each cuisine type, compute both the average and maximum total time (preparation + delivery).

In [82]:
df.groupby("cuisine_type")["order_cost"].mean()

cuisine_type
American          16.319829
Chinese           16.305209
French            19.793889
Indian            16.919726
Italian           16.418691
Japanese          16.304532
Korean            14.001538
Mediterranean     15.474783
Mexican           16.933117
Middle Eastern    18.820612
Southern          19.300588
Spanish           18.994167
Thai              19.207895
Vietnamese        12.882857
Name: order_cost, dtype: float64

In [86]:
df.groupby("cuisine_type").agg({"total_time":["mean","max"]})

               total_time
                     mean max
cuisine_type
American        51.633562  68
Chinese         51.367442  68
French          52.222222  64
Indian          51.191781  65
Italian         52.050336  67
Japanese        51.642553  68
Korean          46.384615  52
Mediterranean   50.586957  64
Mexican         51.116883  65
Middle Eastern  50.755102  67
Southern        51.411765  68
Spanish         50.333333  64
Thai            50.473684  61
Vietnamese      51.857143  59

#### Exercise 10

1. Group the data by both `is_expensive` and the cuisine type, and calculate the total number of orders for each combination.
2. For each value of `is_expensive`, compute the average preparation time and average deliverty time.
3. Create an aggregated summary that groups by the cuisine type and that includes:
   - Mean order cost
   - Mean delivery time
   - Count of orders

In [88]:
df.groupby(["is_expensive", "cuisine_type"]).count()

                             order_id  customer_id  restaurant_name  \
is_expensive cuisine_type
0            American             554          554              554
             Chinese              202          202              202
             French                18           18               18
             Indian                69           69               69
             Italian              286          286              286
             Japanese             443          443              443
             Korean                12           12               12
             Mediterranean         42           42               42
             Mexican               73           73               73
             Middle Eastern        46           46               46
             Southern              16           16               16
             Spanish               12           12               12
             Thai                  18           18               18
             Vietnamese             7            7                7
1            American              30           30               30
             Chinese               13           13               13
             Indian                 4            4                4
             Italian               12           12               12
             Japanese              27           27               27
             Korean                 1            1                1
             Mediterranean          4            4                4
             Mexican                4            4                4
             Middle Eastern         3            3                3
             Southern               1            1                1
             Thai                   1            1                1

                             order_cost  rating  food_preparation_time  \
is_expensive cuisine_type
0            American               554     554                    554
             Chinese                202     202                    202
             French                  18      18                     18
             Indian                  69      69                     69
             Italian                286     286                    286
             Japanese               443     443                    443
             Korean                  12      12                     12
             Mediterranean           42      42                     42
             Mexican                 73      73                     73
             Middle Eastern          46      46                     46
             Southern                16      16                     16
             Spanish                 12      12                     12
             Thai                    18      18                     18
             Vietnamese               7       7                      7
1            American                30      30                     30
             Chinese                 13      13                     13
             Indian                   4       4                      4
             Italian                 12      12                     12
             Japanese                27      27                     27
             Korean                   1       1                      1
             Mediterranean            4       4                      4
             Mexican                  4       4                      4
             Middle Eastern           3       3                      3
             Southern                 1       1                      1
             Thai                     1       1                      1

                             delivery_time  cost_category  total_time  \
is_expensive cuisine_type
0            American                  554            554         554
             Chinese                   202            202         202
             French                     18             18          18
             Indian                     69             69          69
             Italian                   286            286         286
             Japanese                  443            443         443
             Korean                     12             12          12
             Mediterranean              42             42          42
             Mexican                    73             73          73
             Middle Eastern             46             46          46
             Southern                   16             16          16
             Spanish                    12             12          12
             Thai                       18             18          18
             Vietnamese                  7              7           7
1            American                   30             30          30
             Chinese                    13             13          13
             Indian                      4              4           4
             Italian                    12             12          12
             Japanese                   27             27          27
             Korean                      1              1           1
             Mediterranean               4              4           4
             Mexican                     4              4           4
             Middle Eastern              3              3           3
             Southern                    1              1           1
             Thai                        1              1           1

                             fast_favorite  cuisine_short
is_expensive cuisine_type
0            American                  554            554
             Chinese                   202            202
             French                     18             18
             Indian                     69             69
             Italian                   286            286
             Japanese                  443            443
             Korean                     12             12
             Mediterranean              42             42
             Mexican                    73             73
             Middle Eastern             46             46
             Southern                   16             16
             Spanish                    12             12
             Thai                       18             18
             Vietnamese                  7              7
1            American                   30             30
             Chinese                    13             13
             Indian                      4              4
             Italian                    12             12
             Japanese                   27             27
             Korean                      1              1
             Mediterranean               4              4
             Mexican                     4              4
             Middle Eastern              3              3
             Southern                    1              1
             Thai                        1              1

In [92]:
df.groupby("is_expensive")[["food_preparation_time", "delivery_time"]].mean()

              food_preparation_time  delivery_time
is_expensive
0                         27.311457      24.224694
1                         28.460000      23.030000

In [94]:
df.groupby("cuisine_type").agg({"order_cost":"mean", "delivery_time":"mean", "order_id":"count"})

                order_cost  delivery_time  order_id
cuisine_type
American         16.319829      24.193493       584
Chinese          16.305209      23.855814       215
French           19.793889      25.333333        18
Indian           16.919726      24.082192        73
Italian          16.418691      24.567114       298
Japanese         16.304532      24.131915       470
Korean           14.001538      20.923077        13
Mediterranean    15.474783      23.586957        46
Mexican          16.933117      24.389610        77
Middle Eastern   18.820612      24.081633        49
Southern         19.300588      23.823529        17
Spanish          18.994167      23.416667        12
Thai             19.207895      23.157895        19
Vietnamese       12.882857      26.142857         7

#### Exercise 11

Using the Pandas DataFrames provided to you, complete the following:

1. Merge `df_orders` and `df_customers` on `customer_id` using an inner join.
2. How many rows are in the resulting DataFrame?
3. Perform a left join using `df_orders` as the left DataFrame. What differences do you observe compared to the inner join?

In [104]:
df_orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4],
    'customer_id': [101, 102, 103, 104],
    'cost': [25, 40, 15, 30]
})

df_customers = pd.DataFrame({
    'customer_id': [101, 102, 103, 105],
    'customer_name': ['Alice', 'Bob', 'Charlie', 'Diana']
})

df_inner = df_customers.merge(df_orders,on="customer_id")
print(df_inner)

   customer_id customer_name  order_id  cost
0          101         Alice         1    25
1          102           Bob         2    40
2          103       Charlie         3    15

In [106]:
df_left = df_orders.merge(df_customers, on="customer_id", how="left")
print(df_left)

   order_id  customer_id  cost customer_name
0         1          101    25         Alice
1         2          102    40           Bob
2         3          103    15       Charlie
3         4          104    30           NaN

The left join has more observations or records as result than when doing inner

#### Exercise 12

Using the Pandas DataFrames provided to you, complete the following:

1. Merge the two DataFrames where `restaurant_id` matches `rest_id`.
2. Perform an outer join and examine the resulting DataFrame.
3. Identify which rows contain missing values after the merge and explain why they appear.

In [110]:
df_restaurants = pd.DataFrame({
    'restaurant_id': [1, 2, 3],
    'restaurant_name': ['Pizza Place', 'Sushi Spot', 'Burger Joint']
})

df_reviews = pd.DataFrame({
    'rest_id': [1, 1, 2, 4],
    'rating': [4.5, 4.0, 5.0, 3.5]
})

df_match = df_restaurants.merge(df_reviews, left_on="restaurant_id", right_on="rest_id")
print(df_match)

   restaurant_id restaurant_name  rest_id  rating
0              1     Pizza Place        1     4.5
1              1     Pizza Place        1     4.0
2              2      Sushi Spot        2     5.0

In [113]:
df_outer = df_restaurants.merge(df_reviews, left_on="restaurant_id", right_on="rest_id", how="outer")
print(df_outer)

   restaurant_id restaurant_name  rest_id  rating
0            1.0     Pizza Place      1.0     4.5
1            1.0     Pizza Place      1.0     4.0
2            2.0      Sushi Spot      2.0     5.0
3            3.0    Burger Joint      NaN     NaN
4            NaN             NaN      4.0     3.5