### Practice Quiz

#### Part 1

Read in the data found in `diamonds.csv` and then display the first 5 rows of the DataFrame.

In [2]:
import pandas as pd

df = pd.read_csv("../data/diamonds.csv")
df.head()

   carat      cut color clarity  depth  table     x     y     z  price
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43    326
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31    326
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31    327
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63    334
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75    335

#### Part 2

Select all rows where the cut is "Ideal".

In [23]:
df[df["cut"] =="Ideal"]

,carat,cut,color,clarity,depth,table,x,y,z,price,price_per_carat,is_expensive
0,0.23,Ideal,E,SI2,61.5,55.0,3.95,3.98,2.43,326,1417.391304,0
11,0.23,Ideal,J,VS1,62.8,56.0,3.93,3.90,2.46,340,1478.260870,0
13,0.31,Ideal,J,SI2,62.2,54.0,4.35,4.37,2.71,344,1109.677419,0
16,0.30,Ideal,I,SI2,62.0,54.0,4.31,4.34,2.68,348,1160.000000,0
39,0.33,Ideal,I,SI2,61.8,55.0,4.49,4.51,2.78,403,1221.212121,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53925,0.79,Ideal,I,SI1,61.6,56.0,5.95,5.97,3.67,2756,3488.607595,0
53926,0.71,Ideal,E,SI1,61.9,56.0,5.71,5.73,3.54,2756,3881.690141,0
53929,0.71,Ideal,G,VS1,61.4,56.0,5.76,5.73,3.53,2756,3881.690141,0
53935,0.72,Ideal,D,SI1,60.8,57.0,5.75,5.76,3.50,2757,3829.166667,0
53939,0.75,Ideal,D,SI2,62.2,55.0,5.83,5.87,3.64,2757,3676.000000,0

#### Part 3

Create a new column called `price_per_carat` that divides `price` by `carat`. Then output the new DataFrame.

In [19]:
df["price_per_carat"] = df["price"] / df["carat"]
df

,carat,cut,color,clarity,depth,table,x,y,z,price,price_per_carat,is_expensive
0,0.23,Ideal,E,SI2,61.5,55.0,3.95,3.98,2.43,326,1417.391304,0
1,0.21,Premium,E,SI1,59.8,61.0,3.89,3.84,2.31,326,1552.380952,0
2,0.23,Good,E,VS1,56.9,65.0,4.05,4.07,2.31,327,1421.739130,0
3,0.29,Premium,I,VS2,62.4,58.0,4.20,4.23,2.63,334,1151.724138,0
4,0.31,Good,J,SI2,63.3,58.0,4.34,4.35,2.75,335,1080.645161,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,5.75,5.76,3.50,2757,3829.166667,0
53936,0.72,Good,D,SI1,63.1,55.0,5.69,5.75,3.61,2757,3829.166667,0
53937,0.70,Very Good,D,SI1,62.8,60.0,5.66,5.68,3.56,2757,3938.571429,0
53938,0.86,Premium,H,SI2,61.0,58.0,6.15,6.12,3.74,2757,3205.813953,0
53939,0.75,Ideal,D,SI2,62.2,55.0,5.83,5.87,3.64,2757,3676.000000,0

#### Part 4

Use either `apply` or `map` (whichever is more appropriate) to create a new column called `is_expensive` that is 1 if price is greater than 5000 and is 0 otherwise. Then output the new DataFrame.

In [18]:
df["is_expensive"] = df["price"].map(
    lambda x: 1 if x > 5000
    else 0
)
df

,carat,cut,color,clarity,depth,table,x,y,z,price,price_per_carat,is_expensive
0,0.23,Ideal,E,SI2,61.5,55.0,3.95,3.98,2.43,326,1417.391304,0
1,0.21,Premium,E,SI1,59.8,61.0,3.89,3.84,2.31,326,1552.380952,0
2,0.23,Good,E,VS1,56.9,65.0,4.05,4.07,2.31,327,1421.739130,0
3,0.29,Premium,I,VS2,62.4,58.0,4.20,4.23,2.63,334,1151.724138,0
4,0.31,Good,J,SI2,63.3,58.0,4.34,4.35,2.75,335,1080.645161,0
...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,5.75,5.76,3.50,2757,3829.166667,0
53936,0.72,Good,D,SI1,63.1,55.0,5.69,5.75,3.61,2757,3829.166667,0
53937,0.70,Very Good,D,SI1,62.8,60.0,5.66,5.68,3.56,2757,3938.571429,0
53938,0.86,Premium,H,SI2,61.0,58.0,6.15,6.12,3.74,2757,3205.813953,0
53939,0.75,Ideal,D,SI2,62.2,55.0,5.83,5.87,3.64,2757,3676.000000,0

#### Part 5

Calculate and output the average price for each cut.

In [14]:
df.groupby("cut")["price"].mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

#### Part 6

Merge the `students` and `majors` DataFrames so that all information about the students in `students` is kept even if information about their major is not available in `majors`. Output the merged DataFrame.

In [16]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104],
    "name": ["Alice", "Bob", "Charlie", "Diana"]
})

majors = pd.DataFrame({
    "student_id": [101, 102, 105],
    "major": ["Biology", "Computer Science", "Math"]
})
df_left = students.merge(majors, on="student_id", how="left")
print(df_left)

   student_id     name             major
0         101    Alice           Biology
1         102      Bob  Computer Science
2         103  Charlie               NaN
3         104    Diana               NaN